name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
I
      steps:
        - name: Print greeting
          run: echo "Hello World!"
        - name: Print goodbye
          run: echo "Done - bye!"
