name: Minimal Deploy Template

inputs:
  environment_name:
    description: 'Target environment'
    required: true

runs:
  using: "composite"
  steps:
    - name: Test Step
      shell: bash
      run: |
        echo "Testing deployment to ${{ inputs.environment_name }}"
