--CREATING A DATABASE
CREATE DATABASE Bikestores;
GO

-- DROPPING A DATABASE COMMAND
ALTER DATABASE BikeStores
SET SINGLE_USER --Or resticted user
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE BikeStores;
GO
