version: '3'  # Docker Compose file format version

services:
  web:  # Defines the web service (your Flask app)
    build: .  # Build the Docker image from the current directory
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000 (Flask app)
      - "5678:5678"  # Map host port 5678 to container port 5678 (debugger)
    volumes:
      - .:/app  # Mount current directory to /app in the container
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host=0.0.0.0 --port 5000"]