name: Deploy AutoDB Database

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Explicitly checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Development Environment
        uses: ./.github/actions/deploy-template
        with:
          environment_name: "development"
          sql_server: ${{ secrets.DEV_SQL_SERVER }}
          sql_password: ${{ secrets.DEV_SQL_PASSWORD }}
          display_name: "Development Deployment"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: production

    steps:
      # Explicitly checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Production Environment
        uses: ./.github/actions/deploy-template
        with:
          environment_name: "production"
          sql_server: ${{ secrets.PROD_SQL_SERVER }}
          sql_password: ${{ secrets.PROD_SQL_PASSWORD }}
          display_name: "Production Deployment"
