name: Deploy AutoDB Database

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy Development Environment
        uses: ./.github/actions/deploy-template
        with:
          environment_name: "development"
