name: Deploy TimesheetDB and Run SSIS Package

on:
  push:
    branches:
      - main
    paths:
      - 'HandsOnProjects/SQL_Scripts/**'
      - 'HandsOnProjects/Timesheets/**'
  workflow_dispatch:

env:
  DATABASE_NAME: TimesheetDB
  SSIS_FOLDER_NAME: TimesheetDataMigration
  SSIS_PROJECT_NAME: Timesheets
  SSIS_PACKAGE_NAME: DataMigrationFINAL.dtsx
  SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
  SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

jobs:
  deploy-database-and-run-ssis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Execute SQL Script to create database
        run: |
          /opt/mssql-tools/bin/sqlcmd -b -S "${{ env.SQL_SERVER_NAME }}" -U "${{ env.SQL_USERNAME }}" -P "${{ env.SQL_PASSWORD }}" -d master -i HandsOnProjects/SQL_Scripts/TimesheetDB_Creation.sql

      - name: Run SSIS Package from SSISDB (Direct)
        run: |
          /opt/mssql-tools/bin/sqlcmd -S "${{ env.SQL_SERVER_NAME }}" -U "${{ env.SQL_USERNAME }}" -P "${{ env.SQL_PASSWORD }}" -Q "
          DECLARE @execution_id bigint;
          EXEC [SSISDB].[catalog].[create_execution]
              @package_name = N'${{ env.SSIS_PACKAGE_NAME }}',
              @execution_id = @execution_id OUTPUT,
              @folder_name = N'${{ env.SSIS_FOLDER_NAME }}',
              @project_name = N'${{ env.SSIS_PROJECT_NAME }}',
              @use32bitruntime = False,
              @reference_id = NULL;
          EXEC [SSISDB].[catalog].[start_execution] @execution_id;
          "
