name: Test SQL Scripts

on:
  push:
    paths:
      - 'DatabaseAdministration/SQLStatements/*.sql'

jobs:
  test-sql:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --name=mssql-server
          --restart=always

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SQLCMD
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev

    - name: Wait for SQL Server to start
      run: sleep 20  # Wait for SQL Server to be ready

    - name: Run SQL script
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -d master -i DatabaseAdministration/SQLStatements/test.sql
