name: SQL Server Automation

on:
  push:
    branches: [ main ]
    paths:
      - 'DatabaseAdministration/Project/**'
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Network Diagnostics
      shell: cmd
      run: |
        ping -n 3 localhost
        netstat -ano | findstr 1454
        
    - name: Test SQL connection
      shell: cmd
      run: |
        sqlcmd -S "tcp:localhost,1454" -U Auto_user -P "${{ secrets.SQL_PASSWORD }}" -Q "SELECT @@VERSION" -l 30
        
    - name: Run SQL scripts
      shell: cmd
      run: |
        sqlcmd -S "tcp:localhost,1454" -U Auto_user -P "${{ secrets.SQL_PASSWORD }}" -i DatabaseAdministration/Project/scripts/create-user.sql
        sqlcmd -S "tcp:localhost,1454" -U Auto_user -P "${{ secrets.SQL_PASSWORD }}" -i DatabaseAdministration/Project/scripts/create-database.sql
        sqlcmd -S "tcp:localhost,1454" -U Auto_user -P "${{ secrets.SQL_PASSWORD }}" -d AutoTest -i DatabaseAdministration/Project/scripts/create-table.sql
        sqlcmd -S "tcp:localhost,1454" -U Auto_user -P "${{ secrets.SQL_PASSWORD }}" -d AutoTest -i DatabaseAdministration/Project/scripts/stored-procedures.sql
        sqlcmd -S "tcp:localhost,1454" -U Auto_user -P "${{ secrets.SQL_PASSWORD }}" -d AutoTest -i DatabaseAdministration/Project/scripts/insert-data.sql
