name: SQL Server Automation

on:
  push:
    branches: [ main ]
    paths:
      - 'DatabaseAdministration/Project/**'
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run SQL scripts
      run: |
        # Note: Adjust these commands based on your SQL Server setup
        sqlcmd -S localhost -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -i DatabaseAdministration/Project/scripts/create-user.sql
        sqlcmd -S localhost -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -i DatabaseAdministration/Project/scripts/create-database.sql
        sqlcmd -S localhost -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -d AutoTest -i DatabaseAdministration/Project/scripts/create-table.sql
        sqlcmd -S localhost -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -d AutoTest -i DatabaseAdministration/Project/scripts/stored-procedures.sql
        sqlcmd -S localhost -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -d AutoTest -i DatabaseAdministration/Project/scripts/insert-data.sql
