name: SQL Server Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  automate-sql:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install SQL Server tools
      run: choco install sqlserver-cmdlineutils -y
      
    - name: Run SQL scripts
      env:
        SQL_SERVER: localhost
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        sqlcmd -S "$env:SQL_SERVER" -U "$env:SQL_USER" -P "$env:SQL_PASSWORD" -i "DatabaseAdministration/Project/scripts/create_db.sql"
        sqlcmd -S "$env:SQL_SERVER" -U "$env:SQL_USER" -P "$env:SQL_PASSWORD" -d AutoTest -i "DatabaseAdministration/Project/scripts/create_table.sql"
        sqlcmd -S "$env:SQL_SERVER" -U "$env:SQL_USER" -P "$env:SQL_PASSWORD" -d AutoTest -i "DatabaseAdministration/Project/scripts/stored_procedures.sql"
        sqlcmd -S "$env:SQL_SERVER" -U "$env:SQL_USER" -P "$env:SQL_PASSWORD" -d AutoTest -i "DatabaseAdministration/Project/scripts/insert_data.sql"
