name: AutoTest Database Automation

on:
  push:
    paths:
      - 'DatabaseAdministration/Project/**/*.sql'
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows for SQL Server compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SQL Server Authentication
        shell: powershell
        run: |
          $server = "localhost" # Change this if using a remote server
          $database = "AutoTest"
          $user = "Auto_user"
          $password = "YourSecurePassword"

          # Execute SQL Scripts
          Get-ChildItem -Path 'DatabaseAdministration/Project' -Filter "*.sql" | ForEach-Object {
            Write-Output "Executing script $($_.Name)..."
            sqlcmd -S $server -U $user -P $password -d master -i $_.FullName
          }
          Write-Output "Database setup complete!"
