name: Deploy SSIS Package and Run Data Migration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'HandsOnProjects/Timesheets/**'

env:
  SQL_SERVER: 'localhost'
  SSIS_SOURCE_PATH: 'HandsOnProjects/Timesheets/bin/Development/Timesheets.ispac'
  SSIS_DEST_FOLDER: 'NewDataMigration'
  SSIS_PROJECTS_FOLDER: 'Projects'
  JOB_NAME: 'RunNewDataMigrationPackage'
  PACKAGE_NAME: 'DataMigrationFINAL.dtsx'

jobs:
  deploy-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify SSIS Tools (SQL 2022)
        shell: powershell
        run: |
          $ssisPath = "${env:ProgramFiles(x86)}\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe"
          if (-not (Test-Path $ssisPath)) {
              Write-Error "SSIS Deployment Wizard not found at $ssisPath"
              exit 1
          }
          echo "SSIS_PATH=$ssisPath" >> $env:GITHUB_ENV
          Write-Output "Verified SSIS tools at: $ssisPath"

      - name: Debug Working Directory and File Location
        shell: powershell
        run: |
          Write-Output "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          dir "$env:GITHUB_WORKSPACE\HandsOnProjects\Timesheets\bin\Development" -Recurse -ErrorAction Continue

      - name: Create SSIS Catalog Folder (if not exists)
        shell: powershell
        run: |
          $sql = @"
          USE SSISDB
          GO
          SET NOCOUNT ON;
          BEGIN TRY
              IF NOT EXISTS (SELECT 1 FROM [catalog].[folders] WHERE name = '${{ env.SSIS_DEST_FOLDER }}')
              BEGIN
                  EXEC [catalog].[create_folder] @folder_name = N'${{ env.SSIS_DEST_FOLDER }}';
                  SELECT 'Folder created: ${{ env.SSIS_DEST_FOLDER }}' AS Result;
              END
              ELSE
              BEGIN
                  SELECT 'Folder already exists: ${{ env.SSIS_DEST_FOLDER }}' AS Result;
              END
          END TRY
          BEGIN CATCH
              SELECT ERROR_MESSAGE() AS ErrorMessage;
              THROW;
          END CATCH
          GO
          "@
          $result = sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql" -h -1 -W -o "folder_creation.log" 2>&1
          $logContent = Get-Content "folder_creation.log" -Raw
          Write-Output "Folder creation result: $result"
          Write-Output "Folder creation log: $logContent"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to create SSIS catalog folder. Exit code: $LASTEXITCODE. Log: $logContent"
              exit $LASTEXITCODE
          }
          # Check if the result indicates a successful outcome
          if ($result -match "Folder created: ${{ env.SSIS_DEST_FOLDER }}" -or $result -match "Folder already exists: ${{ env.SSIS_DEST_FOLDER }}") {
              Write-Output "Verified folder creation or existence: ${{ env.SSIS_DEST_FOLDER }}"
          } elseif ($result -match "ErrorMessage" -or [string]::IsNullOrEmpty($result)) {
              Write-Error "Unexpected error during folder creation: $result"
              exit 1
          } else {
              Write-Error "Unexpected result during folder creation: $result"
              exit 1
          }
          Start-Sleep -Seconds 30

      - name: Verify SSIS Catalog State
        shell: powershell
        run: |
          $sql = @"
          USE SSISDB
          GO
          SELECT 'Folders' AS ObjectType, name AS Name, NULL AS ProjectName
          FROM [catalog].[folders]
          UNION ALL
          SELECT 'Projects' AS ObjectType, f.name AS FolderName, p.name AS ProjectName
          FROM [catalog].[folders] f
          LEFT JOIN [catalog].[projects] p ON f.folder_id = p.folder_id
          WHERE f.name = '${{ env.SSIS_DEST_FOLDER }}'
          GO
          "@
          $result = sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql" -h -1 -W -o "catalog_state.log" 2>&1
          $logContent = Get-Content "catalog_state.log" -Raw
          Write-Output "SSISDB Catalog State for ${{ env.SSIS_DEST_FOLDER }}:"
          Write-Output $result
          Write-Output "Catalog state log: $logContent"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to query SSIS catalog state. Exit code: $LASTEXITCODE. Log: $logContent"
              exit $LASTEXITCODE
          }
          if ($result -notmatch "${{ env.SSIS_DEST_FOLDER }}") {
              Write-Error "Folder ${{ env.SSIS_DEST_FOLDER }} not found in SSISDB"
              exit 1
          }

      - name: Validate SSIS Connection
        shell: powershell
        run: |
          $testPath = "/${{ env.SSIS_DEST_FOLDER }}"
          Write-Output "Testing connection to path: $testPath"
          $sql = @"
          USE SSISDB
          GO
          SET NOCOUNT ON;
          IF EXISTS (SELECT 1 FROM [catalog].[folders] WHERE name = '${{ env.SSIS_DEST_FOLDER }}')
          BEGIN
              SELECT 'Connection Valid' AS Status
          END
          ELSE
          BEGIN
              SELECT 'Connection Invalid' AS Status
              RAISERROR ('Folder does not exist in SSISDB.', 16, 1);
          END
          GO
          "@
          $maxRetries = 3
          $retryCount = 0
          $success = $false
          while (-not $success -and $retryCount -lt $maxRetries) {
              $result = sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql" -h -1 -W -o "connection_test.log" 2>&1
              $logContent = Get-Content "connection_test.log" -Raw
              Write-Output "Connection test log: $logContent"
              Write-Output "Connection test result: $result"
              if ($LASTEXITCODE -ne 0) {
                  Write-Error "SSIS catalog connection validation failed. Exit code: $LASTEXITCODE. Log: $logContent"
                  exit $LASTEXITCODE
              }
              $trimmedResult = $result.Trim()
              if ($trimmedResult -eq "Connection Valid") {
                  $success = $true
                  Write-Output "SSIS catalog connection validated successfully"
              } else {
                  Write-Output "Retry $($retryCount + 1)/$maxRetries: Folder not yet available"
                  $retryCount++
                  Start-Sleep -Seconds 30
              }
          }
          if (-not $success) {
              Write-Error "SSIS catalog connection validation failed after $maxRetries retries. Result: $trimmedResult"
              exit 1
          }

      - name: Deploy SSIS Package
        shell: powershell
        run: |
          $sourcePath = (Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "HandsOnProjects/Timesheets/bin/Development/Timesheets.ispac").Replace('/', '\')
          if (-not (Test-Path $sourcePath)) {
              Write-Error "SSIS package not found at: $sourcePath"
              exit 1
          }
          Write-Output "Deploying package from: $sourcePath"
          $destinationPath = "/${{ env.SSIS_DEST_FOLDER }}/${{ env.SSIS_PROJECTS_FOLDER }}"
          Write-Output "Destination: ${{ env.SQL_SERVER }} | Path: $destinationPath"
          & "$env:SSIS_PATH" /Silent `
            /SourcePath:"$sourcePath" `
            /DestinationServer:"${{ env.SQL_SERVER }}" `
            /DestinationPath:"$destinationPath" `
            /ModelType:Project
          if ($LASTEXITCODE -ne 0) {
              Write-Error "SSIS deployment failed with exit code $LASTEXITCODE"
              exit $LASTEXITCODE
          }
          Write-Output "SSIS package deployed successfully"

      - name: Create SQL Agent Job
        shell: powershell
        run: |
          $sql = @"
          USE [msdb]
          GO
          IF NOT EXISTS (SELECT 1 FROM sysjobs WHERE name = '${{ env.JOB_NAME }}')
          BEGIN
              EXEC dbo.sp_add_job @job_name = N'${{ env.JOB_NAME }}';
              EXEC sp_add_jobstep
                  @job_name = N'${{ env.JOB_NAME }}',
                  @step_name = N'Run Data Migration',
                  @subsystem = N'SSIS',
                  @command = N'/ISSERVER "\"\SSISDB\${{ env.SSIS_DEST_FOLDER }}\${{ env.SSIS_PROJECTS_FOLDER }}\${{ env.PACKAGE_NAME }}\"" /SERVER "${{ env.SQL_SERVER }}" /Par "\"\$SSISDB\${{ env.SSIS_DEST_FOLDER }}\${{ env.SSIS_PROJECTS_FOLDER }}\${{ env.PACKAGE_NAME }}\"::ServerName(String)";"${{ env.SQL_SERVER }}" /CALLERINFO SQLAGENT /REPORTING E',
                  @database_name = N'master';
              EXEC dbo.sp_add_jobserver @job_name = N'${{ env.JOB_NAME }}';
              SELECT 'Created new job: ${{ env.JOB_NAME }}' AS Result;
          END
          ELSE
          BEGIN
              SELECT 'Job already exists: ${{ env.JOB_NAME }}' AS Result;
          END
          GO
          "@
          $result = sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql" -h -1 -W -o "job_creation.log" 2>&1
          $logContent = Get-Content "job_creation.log" -Raw
          Write-Output "Job creation result: $result"
          Write-Output "Job creation log: $logContent"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to create job. Exit code: $LASTEXITCODE. Log: $logContent"
              exit $LASTEXITCODE
          }
          Write-Output "SQL Agent job setup completed"

      - name: Run Data Migration Job
        shell: powershell
        run: |
          $sql = @"
          EXEC msdb.dbo.sp_start_job @job_name = N'${{ env.JOB_NAME }}';
          SELECT 'Job started: ${{ env.JOB_NAME }}' AS Result;
          "@
          $result = sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql" -h -1 -W -o "job_execution.log" 2>&1
          $logContent = Get-Content "job_execution.log" -Raw
          Write-Output "Job execution result: $result"
          Write-Output "Job execution log: $logContent"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to start job. Exit code: $LASTEXITCODE. Log: $logContent"
              exit $LASTEXITCODE
          }
          Write-Output "Job started successfully. Check SQL Agent for status."
