name: Deploy SSIS Package and Run Data Migration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'HandsOnProjects/Timesheets/**'

env:
  SQL_SERVER: 'localhost'
  SSIS_SOURCE_PATH: 'HandsOnProjects/Timesheets/bin/Development/Timesheets.ispac'
  SSIS_DEST_FOLDER: 'NewDataMigration'
  SSIS_PROJECTS_FOLDER: 'Projects'
  JOB_NAME: 'RunNewDataMigrationPackage'
  PACKAGE_NAME: 'DataMigrationFINAL.dtsx'

jobs:
  deploy-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure SqlServer Module Installed
        shell: powershell
        run: |
          Write-Output "Installing SqlServer module with AllowClobber"
          Install-Module -Name SqlServer -AllowClobber -Force -Scope AllUsers
          Import-Module SqlServer -Force
          Write-Output "SqlServer module installed and loaded."

      - name: Debug Working Directory and File Location
        shell: powershell
        run: |
          Write-Output "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          dir "$env:GITHUB_WORKSPACE\HandsOnProjects\Timesheets\bin\Development" -Recurse -ErrorAction Continue

      - name: Create SSIS Catalog Folder (if not exists)
        shell: powershell
        run: |
          $sql = @"
          USE SSISDB;
          BEGIN TRY
              IF NOT EXISTS (SELECT 1 FROM [catalog].[folders] WHERE name = '${{ env.SSIS_DEST_FOLDER }}')
              BEGIN
                  EXEC [catalog].[create_folder] @folder_name = N'${{ env.SSIS_DEST_FOLDER }}';
                  SELECT 'Folder created: ${{ env.SSIS_DEST_FOLDER }}' AS Result;
              END
              ELSE
              BEGIN
                  SELECT 'Folder already exists: ${{ env.SSIS_DEST_FOLDER }}' AS Result;
              END
          END TRY
          BEGIN CATCH
              THROW;
          END CATCH
          GO
          "@
          sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql"

      - name: Deploy SSIS Package
        shell: powershell
        run: |
          Import-Module SqlServer -Force
          $sourcePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "${{ env.SSIS_SOURCE_PATH }}"
          $sourcePath = $sourcePath.Replace('/', '\')
          if (-not (Test-Path $sourcePath)) {
              Write-Error "SSIS package not found at: $sourcePath"
              exit 1
          }
          Write-Output "Publishing ISPAC file at $sourcePath to SSISDB: ${{ env.SSIS_DEST_FOLDER }}/${{ env.SSIS_PROJECTS_FOLDER }} on ${{ env.SQL_SERVER }}"
          Publish-ISPACProject -Path $sourcePath -Server ${{ env.SQL_SERVER }} -Folder ${{ env.SSIS_DEST_FOLDER }} -Project ${{ env.SSIS_PROJECTS_FOLDER }} -AllowOverwrite
          Write-Output "SSIS package deployed successfully."

      - name: Create SQL Agent Job
        shell: powershell
        run: |
          $sql = @"
          USE [msdb]
          IF NOT EXISTS (SELECT 1 FROM sysjobs WHERE name = '${{ env.JOB_NAME }}')
          BEGIN
              EXEC sp_add_job @job_name = N'${{ env.JOB_NAME }}';
              EXEC sp_add_jobstep
                  @job_name = N'${{ env.JOB_NAME }}',
                  @step_name = N'Run Data Migration',
                  @subsystem = N'SSIS',
                  @command = N'/ISSERVER "\"\SSISDB\${{ env.SSIS_DEST_FOLDER }}\${{ env.SSIS_PROJECTS_FOLDER }}\${{ env.PACKAGE_NAME }}\"" /SERVER "${{ env.SQL_SERVER }}"',
                  @database_name = N'master';
              EXEC sp_add_jobserver @job_name = N'${{ env.JOB_NAME }}';
              SELECT 'Created new job: ${{ env.JOB_NAME }}' AS Result;
          END
          ELSE
          BEGIN
              SELECT 'Job already exists: ${{ env.JOB_NAME }}' AS Result;
          END
          "@
          sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql"

      - name: Run Data Migration Job
        shell: powershell
        run: |
          $sql = "EXEC msdb.dbo.sp_start_job @job_name = N'${{ env.JOB_NAME }}'; SELECT 'Job started: ${{ env.JOB_NAME }}' AS Result;"
          sqlcmd -S "${{ env.SQL_SERVER }}" -Q "$sql"
