name: Deploy SSIS Package and Run Data Migration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'HandsOnProjects/Timesheets/**'

env:
  SQL_SERVER: 'localhost'
  SSIS_SOURCE_PATH: 'HandsOnProjects/Timesheets/bin/Development/Timesheets.ispac'
  SSIS_DEST_FOLDER: 'TimesheetDataMigration'  # Just the folder name
  SSIS_PROJECT: 'Timesheets'                 # Just the project name
  JOB_NAME: 'RunDataMigrationPackage'
  PACKAGE_NAME: 'DataMigrationFINAL.dtsx'

jobs:
  deploy-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: sc_PaballoPholo_2025  # Ensure correct repository name
          path: sc_PaballoPholo_2025        # Set the checkout path to avoid duplication

      - name: Verify SSIS Tools (SQL 2022)
        shell: powershell
        run: |
          # Correct path for SQL Server 2022
          $ssisPath = "${env:ProgramFiles(x86)}\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe"
          if (-not (Test-Path $ssisPath)) {
              Write-Error "SSIS Deployment Wizard not found at $ssisPath"
              exit 1
          }
          echo "SSIS_PATH=$ssisPath" >> $env:GITHUB_ENV
          Write-Output "Verified SSIS tools at: $ssisPath"

      - name: Debug Working Directory and File Location
        shell: powershell
        run: |
          Write-Output "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          dir "$env:GITHUB_WORKSPACE\sc_PaballoPholo_2025\HandsOnProjects\Timesheets\bin\Development" -Recurse -ErrorAction Continue

      - name: Deploy SSIS Package
        shell: powershell
        run: |
          # Use the full path from the repository root, adjusting for checkout path
          $repoRoot = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "sc_PaballoPholo_2025"
          $sourcePath = (Join-Path -Path $repoRoot -ChildPath "HandsOnProjects/Timesheets/bin/Development/Timesheets.ispac").Replace('/', '\')
          if (-not (Test-Path $sourcePath)) {
              Write-Error "SSIS package not found at: $sourcePath"
              exit 1
          }
          Write-Output "Deploying package from: $sourcePath"
          Write-Output "Destination: ${{ env.SQL_SERVER }} | Folder: ${{ env.SSIS_DEST_FOLDER }} | Project: ${{ env.SSIS_PROJECT }}"

          & "$env:SSIS_PATH" /Silent `
            /SourcePath:"$sourcePath" `
            /DestinationServer:"${{ env.SQL_SERVER }}" `
            /DestinationPath:"/${{ env.SSIS_DEST_FOLDER }}/${{ env.SSIS_PROJECT }}" `
            /ModelType:Project

          if ($LASTEXITCODE -ne 0) {
              Write-Error "SSIS deployment failed with exit code $LASTEXITCODE"
              exit $LASTEXITCODE
          }
          Write-Output "SSIS package deployed successfully"

      - name: Create SQL Agent Job
        shell: powershell
        run: |
          $sql = @"
          USE [msdb]
          GO
          IF NOT EXISTS (SELECT 1 FROM sysjobs WHERE name = '${{ env.JOB_NAME }}')
          BEGIN
              EXEC dbo.sp_add_job @job_name = N'${{ env.JOB_NAME }}';
              
              EXEC sp_add_jobstep
                  @job_name = N'${{ env.JOB_NAME }}',
                  @step_name = N'Run Data Migration',
                  @subsystem = N'SSIS',
                  @command = N'/ISSERVER "\"\SSISDB\${{ env.SSIS_DEST_FOLDER }}\${{ env.SSIS_PROJECT }}\${{ env.PACKAGE_NAME }}\"" /SERVER "${{ env.SQL_SERVER }}" /Par "\"\$SSISDB\${{ env.SSIS_DEST_FOLDER }}\${{ env.SSIS_PROJECT }}\${{ env.PACKAGE_NAME }}\"::ServerName(String)";"${{ env.SQL_SERVER }}" /CALLERINFO SQLAGENT /REPORTING E',
                  @database_name = N'master';
              
              EXEC dbo.sp_add_jobserver @job_name = N'${{ env.JOB_NAME }}';
              Write-Output "Created new job: ${{ env.JOB_NAME }}"
          END
          GO
          "@

          sqlcmd -S "${{ env.SQL_SERVER }}" -U "${{ secrets.SQL_USERNAME }}" -P "${{ secrets.SQL_PASSWORD }}" -Q "$sql"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to create job"
              exit $LASTEXITCODE
          }

      - name: Run Data Migration Job
        shell: powershell
        run: |
          sqlcmd -S "${{ env.SQL_SERVER }}" -U "${{ secrets.SQL_USERNAME }}" -P "${{ secrets.SQL_PASSWORD }}" `
            -Q "EXEC msdb.dbo.sp_start_job @job_name='${{ env.JOB_NAME }}'"
          
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to start job"
              exit $LASTEXITCODE
          }
          Write-Output "Job started successfully. Check SQL Agent for status."
